<?php

/*
|--------------------------------------------------------------------------
| DO NOT EDIT THIS FILE DIRECTLY.
|--------------------------------------------------------------------------
*/


return array(

    'Global Manager' => array(
        array(
            'permission' => 'superuser',
            'label' => 'Super User',
            'note' => 'Determines whether the user has full access to all aspects of the admin. This setting overrides any more specific permissions throughout the system. ',
            'display' => true,
        ),
    ),

    'Admin Manager' => array(
        array(
            'permission' => 'admin',
            'label' => 'Administrator',
            'note' => 'This user has access to most aspects of the admin. ',
            'display' => true,
        )
    ),
    // Reports
    'Reports manager' => array(
        array(
            'permission' => 'reports.view',
            'label' => 'View Report',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'reports.create',
            'label' => 'Create Report',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'reports.edit',
            'label' => 'Edit Report',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'reports.update',
            'label' => 'Update Report',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'reports.delete',
            'label' => 'Delete Report',
            'note' => '',
            'display' => true,
        ),
    ),
// Expenses
    'Expense manager' => array(
        array(
            'permission' => 'expenses.view',
            'label' => 'View Expense',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'expenses.create',
            'label' => 'Create Expense',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'expenses.edit',
            'label' => 'Edit Expense',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'expenses.update',
            'label' => 'Update Expense',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'expenses.delete',
            'label' => 'Delete Expense',
            'note' => '',
            'display' => true,
        ),
    ),
// Invoices
    'Invoice manager' => array(
        array(
            'permission' => 'invoices.view',
            'label' => 'View Invoices',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'invoices.create',
            'label' => 'Create Invoices',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'invoices.edit',
            'label' => 'Edit Invoices',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'invoices.update',
            'label' => 'Update Invoices',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'invoices.delete',
            'label' => 'Delete Invoices',
            'note' => '',
            'display' => true,
        ),
    ),
// Suppliers
    'Supplier manager' => array(
        array(
            'permission' => 'vendors.view',
            'label' => 'View Supplier',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'vendors.create',
            'label' => 'Create Supplier',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'vendors.edit',
            'label' => 'Edit Supplier',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'vendors.update',
            'label' => 'Update Supplier',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'vendors.delete',
            'label' => 'Delete Supplier',
            'note' => '',
            'display' => true,
        ),
    ),
// Suppliers contact
    'Supplier Contact manager' => array(
        array(
            'permission' => 'vendor_contacts.view',
            'label' => 'View Supplier Contact',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'vendor_contacts.create',
            'label' => 'Create Supplier Contact',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'vendor_contacts.edit',
            'label' => 'Edit Supplier Contact',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'vendor_contacts.update',
            'label' => 'Update Supplier Contact',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'vendor_contacts.delete',
            'label' => 'Delete Supplier Contact',
            'note' => '',
            'display' => true,
        ),
    ),
// Clients
    'Client manager' => array(
        array(
            'permission' => 'clients.view',
            'label' => 'View Client',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'clients.create',
            'label' => 'Create Client',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'clients.edit',
            'label' => 'Edit Client',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'clients.update',
            'label' => 'Update Client',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'clients.delete',
            'label' => 'Delete Client',
            'note' => '',
            'display' => true,
        ),
    ),
// Clients contact
    'Client Contact manager' => array(
        array(
            'permission' => 'client_contacts.view',
            'label' => 'View Client Contact',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'client_contacts.create',
            'label' => 'Create Client Contact',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'client_contacts.edit',
            'label' => 'Edit Client Contact',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'client_contacts.update',
            'label' => 'Update Client Contact',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'client_contacts.delete',
            'label' => 'Delete Client Contact',
            'note' => '',
            'display' => true,
        ),
    ),
// Item price management
    'Item prices manager' => array(
        array(
            'permission' => 'item_prices.view',
            'label' => 'View item prices',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_prices.create',
            'label' => 'Create item prices',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_prices.edit',
            'label' => 'Edit item prices',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_prices.update',
            'label' => 'Update item prices',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_prices.delete',
            'label' => 'Delete item prices',
            'note' => '',
            'display' => true,
        ),
    ),
// Item management
    'Items manager' => array(
        array(
            'permission' => 'products.view',
            'label' => 'View items',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'products.create',
            'label' => 'Create items',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'products.edit',
            'label' => 'Edit items',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'products.update',
            'label' => 'Update items',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'products.delete',
            'label' => 'Delete items',
            'note' => '',
            'display' => true,
        ),
    ),
//   item categories
    'Item categories manager' => array(
        array(
            'permission' => 'item_categories.view',
            'label' => 'View item category',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_categories.create',
            'label' => 'Create item category',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_categories.edit',
            'label' => 'Edit item category',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_categories.update',
            'label' => 'Update item category',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_categories.delete',
            'label' => 'Delete item category',
            'note' => '',
            'display' => true,
        ),
    ),
    //   item brands
    'Item brands manager' => array(
        array(
            'permission' => 'item_brands.view',
            'label' => 'View item property',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_brands.create',
            'label' => 'Create item property',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_brands.edit',
            'label' => 'Edit item property',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_brands.update',
            'label' => 'Update item property',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_brands.delete',
            'label' => 'Delete item property',
            'note' => '',
            'display' => true,
        ),
    ),
//  stores
    'Stores manager' => array(
        array(
            'permission' => 'stores.view',
            'label' => 'View store',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'stores.create',
            'label' => 'Create store',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'stores.edit',
            'label' => 'Edit store',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'stores.update',
            'label' => 'Update store',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'stores.delete',
            'label' => 'Delete store',
            'note' => '',
            'display' => true,
        ),
    ),
//    item stores
    'Item stores manager' => array(
        array(
            'permission' => 'item_stores.view',
            'label' => 'View item store',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_stores.create',
            'label' => 'Create item store',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_stores.edit',
            'label' => 'Edit item store',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_stores.update',
            'label' => 'Update item store',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_stores.delete',
            'label' => 'Delete item store',
            'note' => '',
            'display' => true,
        ),

    ),
//    item request
    'Item requests manager' => array(
        array(
            'permission' => 'item_requests.view',
            'label' => 'View item request',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_requests.create',
            'label' => 'Create item request',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_requests.edit',
            'label' => 'Edit item request',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_requests.update',
            'label' => 'Update item request',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_requests.delete',
            'label' => 'Delete item request',
            'note' => '',
            'display' => true,
        ),
    ),
// item transfer
    'Item transfers manager' => array(
        array(
            'permission' => 'item_transfers.view',
            'label' => 'View item transfer',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_transfers.create',
            'label' => 'Create item transfer',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_transfers.edit',
            'label' => 'Edit item transfer',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_transfers.update',
            'label' => 'Update item transfer',
            'note' => '',
            'display' => true,
        ),

        array(
            'permission' => 'item_transfers.delete',
            'label' => 'Delete item transfer',
            'note' => '',
            'display' => true,
        ),
    ),
    // item discount category
    'Discount category manager' => array(
        array(
            'permission' => 'discount_categories.view',
            'label' => 'View discount category',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'discount_categories.create',
            'label' => 'Create discount category',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'discount_categories.edit',
            'label' => 'Edit discount category',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'discount_categories.update',
            'label' => 'Update discount category',
            'note' => '',
            'display' => true,
        ),

        array(
            'permission' => 'discount_categories.delete',
            'label' => 'Delete discount category',
            'note' => '',
            'display' => true,
        ),
    ),
    // Tax Category management
    'Tax category manager' => array(
        array(
            'permission' => 'tax_categories.view',
            'label' => 'View tax categories',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_categories.create',
            'label' => 'Create tax categories',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_categories.edit',
            'label' => 'Edit tax categories',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_categories.update',
            'label' => 'Update tax categories',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_categories.delete',
            'label' => 'Delete tax categories',
            'note' => '',
            'display' => true,
        ),
    ),
//  tax province
    'Tax province manager' => array(
        array(
            'permission' => 'tax_provinces.view',
            'label' => 'View tax province',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_provinces.create',
            'label' => 'Create tax province',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_provinces.edit',
            'label' => 'Edit tax province',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_provinces.update',
            'label' => 'Update tax province',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_provinces.delete',
            'label' => 'Delete tax province',
            'note' => '',
            'display' => true,
        ),
    ),

// tax authority
    'Tax authority manager' => array(
        array(
            'permission' => 'tax_authorities.view',
            'label' => 'View tax authority',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_authorities.create',
            'label' => 'Create tax authority',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_authorities.edit',
            'label' => 'Edit tax authority',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_authorities.update',
            'label' => 'Update tax authority',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_authorities.delete',
            'label' => 'Delete tax authority',
            'note' => '',
            'display' => true,
        ),
    ),

//  tax auth rate
    'Tax authority rate manager' => array(
        array(
            'permission' => 'tax_authority_rates.view',
            'label' => 'View tax auth rate',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_authority_rates.create',
            'label' => 'Create tax auth rate',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_authority_rates.edit',
            'label' => 'Edit tax auth rate',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_authority_rates.update',
            'label' => 'Update tax auth rate',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_authority_rates.delete',
            'label' => 'Delete tax auth rate',
            'note' => '',
            'display' => true,
        ),
    ),

//   chart permission_groups
    'Chart permission_groups manager' => array(
        array(
            'permission' => 'sales_type.view',
            'label' => 'View sales type',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'chart_groups.create',
            'label' => 'Create chart group',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'chart_groups.edit',
            'label' => 'Edit chart group',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'chart_groups.update',
            'label' => 'Update chart group',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'chart_groups.delete',
            'label' => 'Delete chart group',
            'note' => '',
            'display' => true,
        ),
    ),
//   chart master
    'Chart master manager' => array(
        array(
            'permission' => 'chart_master.view',
            'label' => 'View chart master',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'chart_master.create',
            'label' => 'Create chart master',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'chart_master.edit',
            'label' => 'Edit chart master',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'chart_master.update',
            'label' => 'Update chart master',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'chart_master.delete',
            'label' => 'Delete chart master',
            'note' => '',
            'display' => true,
        ),
    ),
//  sales type
    'Sales type manager' => array(
        array(
            'permission' => 'sales_type.view',
            'label' => 'View sales type',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'sales_type.create',
            'label' => 'Create sales type',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'sales_type.edit',
            'label' => 'Edit sales type',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'sales_type.update',
            'label' => 'Update sales type',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'sales_type.delete',
            'label' => 'Delete sales type',
            'note' => '',
            'display' => true,
        ),
    ),

    // account group
    'user permission group' => array(
        array(
            'permission' => 'permission_groups.view',
            'label' => 'View permission_groups',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'permission_groups.create',
            'label' => 'Create permission_groups',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'permission_groups.edit',
            'label' => 'Edit permission_groups',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'permission_groups.update',
            'label' => 'update permission_groups',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'permission_groups.delete',
            'label' => 'Delete permission_groups',
            'note' => '',
            'display' => true,
        ),
    ),

// account permission
    'Users manager' => array(
        array(
            'permission' => 'users.view',
            'label' => 'View Users',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'users.create',
            'label' => 'Create Users',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'users.edit',
            'label' => 'Edit Users',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'users.update',
            'label' => 'Update Users',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'users.delete',
            'label' => 'Delete Users',
            'note' => '',
            'display' => true,
        ),
    ),
//    Division manager
    'Divisions manager' => array(
        array(
            'permission' => 'divisions.view',
            'label' => 'View divisions',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'divisions.create',
            'label' => 'Create divisions',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'divisions.edit',
            'label' => 'Edit divisions',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'divisions.update',
            'label' => 'Update divisions',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'divisions.delete',
            'label' => 'Delete divisions',
            'note' => '',
            'display' => true,
        ),
    ),
// department permission
    'Departments manager' => array(
        array(
            'permission' => 'departments.view',
            'label' => 'View departments',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'departments.create',
            'label' => 'Create departments',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'departments.edit',
            'label' => 'Edit departments',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'departments.update',
            'label' => 'Update departments',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'departments.delete',
            'label' => 'Delete departments',
            'note' => '',
            'display' => true,
        ),
    ),
    // section permission
    'Sections manager' => array(
        array(
            'permission' => 'sections.view',
            'label' => 'View sections',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'sections.create',
            'label' => 'Create sections',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'sections.edit',
            'label' => 'Edit sections',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'sections.update',
            'label' => 'Update sections',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'sections.delete',
            'label' => 'Delete sections',
            'note' => '',
            'display' => true,
        ),
    ),
//    Manufacturer management
    'Manufacturers manager' => array(
        array(
            'permission' => 'manufacturers.view',
            'label' => 'View manufacturers',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'manufacturers.create',
            'label' => 'Create manufacturers',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'manufacturers.edit',
            'label' => 'Edit manufacturers',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'manufacturers.update',
            'label' => 'Update manufacturers',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'manufacturers.delete',
            'label' => 'Delete manufacturers',
            'note' => '',
            'display' => true,
        ),
    ),
//Company management
    'Companies manager' => array(
        array(
            'permission' => 'companies.view',
            'label' => 'View companies',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'companies.create',
            'label' => 'Create companies',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'companies.edit',
            'label' => 'Edit companies',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'companies.update',
            'label' => 'Update companies',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'companies.delete',
            'label' => 'Delete companies',
            'note' => '',
            'display' => true,
        ),
    ),
    //Location management
    'Locations manager' => array(
        array(
            'permission' => 'locations.view',
            'label' => 'View locations',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'locations.create',
            'label' => 'Create locations',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'locations.edit',
            'label' => 'Edit locations',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'locations.update',
            'label' => 'Update locations',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'locations.delete',
            'label' => 'Delete locations',
            'note' => '',
            'display' => true,
        ),
    ),
//    Action log management
    'Action logs manager' => array(
        array(
            'permission' => 'action_logs.view',
            'label' => 'View action logs',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'action_logs.create',
            'label' => 'Create action logs',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'action_logs.edit',
            'label' => 'Edit action logs',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'action_logs.update',
            'label' => 'Update action logs',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'action_logs.delete',
            'label' => 'Delete action logs',
            'note' => '',
            'display' => true,
        ),
    ),
// item movements
    'Item movements manager' => array(
        array(
            'permission' => 'item_movements.view',
            'label' => 'View item movements',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_movements.create',
            'label' => 'Create item movements',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_movements.edit',
            'label' => 'Edit item movements',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_movements.update',
            'label' => 'Update item movements',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_movements.delete',
            'label' => 'Delete item movements',
            'note' => '',
            'display' => true,
        ),
    ),
// item transfers
    'Item transfers manager' => array(
        array(
            'permission' => 'item_transfers.view',
            'label' => 'View item transfers',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_transfers.create',
            'label' => 'Create item transfers',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_transfers.edit',
            'label' => 'Edit item transfers',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_transfers.update',
            'label' => 'Update item transfers',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_transfers.delete',
            'label' => 'Delete item transfers',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'transfer.approve',
            'label' => 'Item transfer approval',
            'note' => '',
            'display' => true,
        ),
    ),
//  UOM
    'Unit of measure manager' => array(
        array(
            'permission' => 'units.view',
            'label' => 'View units',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'units.create',
            'label' => 'Create units',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'units.edit',
            'label' => 'Edit units',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'units.update',
            'label' => 'Update units',
            'note' => '',
            'display' => true,
        ),

        array(
            'permission' => 'units.delete',
            'label' => 'Delete units',
            'note' => '',
            'display' => true,
        ),
    ),
);
