<?php

/*
|--------------------------------------------------------------------------
| DO NOT EDIT THIS FILE DIRECTLY.
|--------------------------------------------------------------------------
*/


return array(

    'Master account' => array(
        array(
            'permission' => 'superuser',
            'label' => 'Super User',
            'note' => 'Determines whether the user has full access to all aspects of the admin. This setting overrides any more specific permissions throughout the system. ',
            'display' => true,
        ),
    ),

    'Administrator Privilege' => array(
        array(
            'permission' => 'admin',
            'label' => 'Admin',
            'note' => 'This user has access to most aspects of the admin. ',
            'display' => true,
        )
    ),
    // Reports
    'Reports Privilege' => array(
        array(
            'permission' => 'reports.view',
            'label' => 'View Report',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'reports.create',
            'label' => 'Create Report',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'reports.edit',
            'label' => 'Edit Report',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'reports.delete',
            'label' => 'Delete Report',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'reports.settings',
            'label' => 'Report Settings',
            'note' => '',
            'display' => true,
        ),
    ),
// Expenses
    'Expense Privilege' => array(
        array(
            'permission' => 'expenses.view',
            'label' => 'View Expense',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'expenses.create',
            'label' => 'Create Expense',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'expenses.edit',
            'label' => 'Edit Expense',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'expenses.delete',
            'label' => 'Delete Expense',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'expenses.settings',
            'label' => 'Expense Settings',
            'note' => '',
            'display' => true,
        ),
    ),
// expense category
    'Expense Category Privilege' => array(
        array(
            'permission' => 'expense_categories.view',
            'label' => 'View Expense Category',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'expense_categories.create',
            'label' => 'Create Expense Category',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'expense_categories.edit',
            'label' => 'Edit Expense Category',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'expense_categories.delete',
            'label' => 'Delete Expense Category',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'expense_categories.settings',
            'label' => 'Expense Category Settings',
            'note' => '',
            'display' => true,
        ),
    ),
// Invoices
    'Invoice Privilege' => array(
        array(
            'permission' => 'invoices.view',
            'label' => 'View Invoices',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'invoices.create',
            'label' => 'Create Invoices',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'invoices.edit',
            'label' => 'Edit Invoices',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'invoices.delete',
            'label' => 'Delete Invoices',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'invoices.settings',
            'label' => 'Invoice Settings',
            'note' => '',
            'display' => true,
        ),
    ),
// Suppliers
    'Supplier Privilege' => array(
        array(
            'permission' => 'vendors.view',
            'label' => 'View Supplier',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'vendors.create',
            'label' => 'Create Supplier',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'vendors.edit',
            'label' => 'Edit Supplier',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'vendors.delete',
            'label' => 'Delete Supplier',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'vendors.settings',
            'label' => 'Vendor Settings',
            'note' => '',
            'display' => true,
        ),
    ),
// Suppliers contact
    'Supplier Contact Privilege' => array(
        array(
            'permission' => 'vendor_contacts.view',
            'label' => 'View Supplier Contact',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'vendor_contacts.create',
            'label' => 'Create Supplier Contact',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'vendor_contacts.edit',
            'label' => 'Edit Supplier Contact',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'vendor_contacts.delete',
            'label' => 'Delete Supplier Contact',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'vendor_contacts.settings',
            'label' => 'Vendor Contact Settings',
            'note' => '',
            'display' => true,
        ),
    ),
// Clients
    'Client Privilege' => array(
        array(
            'permission' => 'clients.view',
            'label' => 'View Client',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'clients.create',
            'label' => 'Create Client',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'clients.edit',
            'label' => 'Edit Client',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'clients.delete',
            'label' => 'Delete Client',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'clients.settings',
            'label' => 'Client Settings',
            'note' => '',
            'display' => true,
        ),
    ),
// Clients contact
    'Client Contact Privilege' => array(
        array(
            'permission' => 'client_contacts.view',
            'label' => 'View Client Contact',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'client_contacts.create',
            'label' => 'Create Client Contact',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'client_contacts.edit',
            'label' => 'Edit Client Contact',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'client_contacts.delete',
            'label' => 'Delete Client Contact',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'client_contacts.settings',
            'label' => 'Client Contact Settings',
            'note' => '',
            'display' => true,
        ),
    ),
// Item price management
    'Item Prices Privilege' => array(
        array(
            'permission' => 'item_prices.view',
            'label' => 'View item prices',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_prices.create',
            'label' => 'Create item prices',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_prices.edit',
            'label' => 'Edit item prices',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_prices.delete',
            'label' => 'Delete item prices',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_prices.settings',
            'label' => 'Item Price Settings',
            'note' => '',
            'display' => true,
        ),
    ),
// Item management
    'Items Privilege' => array(
        array(
            'permission' => 'products.view',
            'label' => 'View items',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'products.create',
            'label' => 'Create items',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'products.edit',
            'label' => 'Edit items',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'products.delete',
            'label' => 'Delete items',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'products.settings',
            'label' => 'Item Settings',
            'note' => '',
            'display' => true,
        ),
    ),
//   item categories
    'Item Categories Privilege' => array(
        array(
            'permission' => 'item_categories.view',
            'label' => 'View item category',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_categories.create',
            'label' => 'Create item category',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_categories.edit',
            'label' => 'Edit item category',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_categories.delete',
            'label' => 'Delete item category',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_categories.settings',
            'label' => 'Item Category Settings',
            'note' => '',
            'display' => true,
        ),
    ),
    //   item brands
    'Item Brands Privilege' => array(
        array(
            'permission' => 'item_brands.view',
            'label' => 'View Item Brand',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_brands.create',
            'label' => 'Create Item Brand',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_brands.edit',
            'label' => 'Edit Item Brand',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_brands.delete',
            'label' => 'Delete Item Brand',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_brands.settings',
            'label' => 'Item Brand Settings',
            'note' => '',
            'display' => true,
        ),
    ),
//  stores
    'Stores Privilege' => array(
        array(
            'permission' => 'stores.view',
            'label' => 'View store',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'stores.create',
            'label' => 'Create store',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'stores.edit',
            'label' => 'Edit store',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'stores.delete',
            'label' => 'Delete store',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'stores.settings',
            'label' => 'Store Settings',
            'note' => '',
            'display' => true,
        ),
    ),
//    item stores
    'Item Stores Privilege' => array(
        array(
            'permission' => 'item_stores.view',
            'label' => 'View item store',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_stores.create',
            'label' => 'Create item store',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_stores.edit',
            'label' => 'Edit item store',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_stores.delete',
            'label' => 'Delete item store',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_stores.settings',
            'label' => 'Item Store Settings',
            'note' => '',
            'display' => true,
        ),

    ),
//    item request
    'Item Requests Privilege' => array(
        array(
            'permission' => 'item_requests.view',
            'label' => 'View item request',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_requests.create',
            'label' => 'Create item request',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_requests.edit',
            'label' => 'Edit item request',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_requests.delete',
            'label' => 'Delete item request',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_requests.settings',
            'label' => 'Item Request Settings',
            'note' => '',
            'display' => true,
        ),
    ),
    // item discount category
    'Discount Category Privilege' => array(
        array(
            'permission' => 'discount_categories.view',
            'label' => 'View discount category',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'discount_categories.create',
            'label' => 'Create discount category',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'discount_categories.edit',
            'label' => 'Edit discount category',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'discount_categories.delete',
            'label' => 'Delete discount category',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'discount_categories.settings',
            'label' => 'Discount Category Settings',
            'note' => '',
            'display' => true,
        ),
    ),
    // Tax Category management
    'Tax Category Privilege' => array(
        array(
            'permission' => 'tax_categories.view',
            'label' => 'View Tax Categories',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_categories.create',
            'label' => 'Create Tax Categories',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_categories.edit',
            'label' => 'Edit Tax Categories',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_categories.delete',
            'label' => 'Delete Tax Categories',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_categories.settings',
            'label' => 'Tax Category Settings',
            'note' => '',
            'display' => true,
        ),
    ),
//  Tax Province
    'Tax Province Privilege' => array(
        array(
            'permission' => 'tax_provinces.view',
            'label' => 'View Tax Province',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_provinces.create',
            'label' => 'Create Tax Province',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_provinces.edit',
            'label' => 'Edit Tax Province',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_provinces.delete',
            'label' => 'Delete Tax Province',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_provinces.settings',
            'label' => 'Tax Province Settings',
            'note' => '',
            'display' => true,
        ),
    ),

// Tax Authority
    'Tax Authority Privilege' => array(
        array(
            'permission' => 'tax_authorities.view',
            'label' => 'View Tax Authority',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_authorities.create',
            'label' => 'Create Tax Authority',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_authorities.edit',
            'label' => 'Edit Tax Authority',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_authorities.delete',
            'label' => 'Delete Tax Authority',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_authorities.settings',
            'label' => 'Tax Authority Settings',
            'note' => '',
            'display' => true,
        ),
    ),

//  Tax Auth Rate
    'Tax Authority Rate Privilege' => array(
        array(
            'permission' => 'tax_authority_rates.view',
            'label' => 'View Tax Auth Rate',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_authority_rates.create',
            'label' => 'Create Tax Auth Rate',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_authority_rates.edit',
            'label' => 'Edit Tax Auth Rate',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_authority_rates.delete',
            'label' => 'Delete Tax Auth Rate',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'tax_authority_rates.settings',
            'label' => 'Tax Authority Rate Settings',
            'note' => '',
            'display' => true,
        ),
    ),

//   chart permission_groups
    'Chart Group Privilege' => array(
        array(
            'permission' => 'chart_groups.view',
            'label' => 'View Sales Type',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'chart_groups.create',
            'label' => 'Create Chart Group',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'chart_groups.edit',
            'label' => 'Edit Chart Group',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'chart_groups.delete',
            'label' => 'Delete Chart Group',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'chart_groups.settings',
            'label' => 'Chart Group Settings',
            'note' => '',
            'display' => true,
        ),
    ),
//   Chart Master
    'Chart Master Privilege' => array(
        array(
            'permission' => 'chart_master.view',
            'label' => 'View Chart Master',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'chart_master.create',
            'label' => 'Create Chart Master',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'chart_master.edit',
            'label' => 'Edit Chart Master',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'chart_master.delete',
            'label' => 'Delete Chart Master',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'chart_master.settings',
            'label' => 'Chart Master Settings',
            'note' => '',
            'display' => true,
        ),
    ),
//  Sales Type
    'Sales Type Privilege' => array(
        array(
            'permission' => 'sales_type.view',
            'label' => 'View Sales Type',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'sales_type.create',
            'label' => 'Create Sales Type',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'sales_type.edit',
            'label' => 'Edit Sales Type',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'sales_type.delete',
            'label' => 'Delete Sales Type',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'sales_type.settings',
            'label' => 'Sale Type Settings',
            'note' => '',
            'display' => true,
        ),
    ),

    // account group
    'Permission group' => array(
        array(
            'permission' => 'permission_groups.view',
            'label' => 'View Permission Group',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'permission_groups.create',
            'label' => 'Create Permission Group',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'permission_groups.edit',
            'label' => 'Edit Permission Group',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'permission_groups.delete',
            'label' => 'Delete Permission Group',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'permission_groups.settings',
            'label' => 'Permission Group Settings',
            'note' => '',
            'display' => true,
        ),
    ),

// account permission
    'Users Privilege' => array(
        array(
            'permission' => 'users.view',
            'label' => 'View User',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'users.create',
            'label' => 'Create User',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'users.edit',
            'label' => 'Edit User',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'users.delete',
            'label' => 'Delete User',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'users.settings',
            'label' => 'User Settings',
            'note' => '',
            'display' => true,
        ),
    ),
//    Division privilege
    'Divisions Privilege' => array(
        array(
            'permission' => 'divisions.view',
            'label' => 'View divisions',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'divisions.create',
            'label' => 'Create divisions',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'divisions.edit',
            'label' => 'Edit divisions',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'divisions.delete',
            'label' => 'Delete divisions',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'divisions.settings',
            'label' => 'Division Settings',
            'note' => '',
            'display' => true,
        ),
    ),
// department permission
    'Departments Privilege' => array(
        array(
            'permission' => 'departments.view',
            'label' => 'View Department',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'departments.create',
            'label' => 'Create Department',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'departments.edit',
            'label' => 'Edit Department',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'departments.delete',
            'label' => 'Delete Department',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'departments.settings',
            'label' => 'Department Settings',
            'note' => '',
            'display' => true,
        ),
    ),
    // section permission
    'Sections Privilege' => array(
        array(
            'permission' => 'sections.view',
            'label' => 'View Section',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'sections.create',
            'label' => 'Create Section',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'sections.edit',
            'label' => 'Edit Section',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'sections.delete',
            'label' => 'Delete Section',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'sections.settings',
            'label' => 'Section Settings',
            'note' => '',
            'display' => true,
        ),
    ),
//    Manufacturer management
    'Manufacturers Privilege' => array(
        array(
            'permission' => 'manufacturers.view',
            'label' => 'View Manufacturer',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'manufacturers.create',
            'label' => 'Create Manufacturer',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'manufacturers.edit',
            'label' => 'Edit Manufacturer',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'manufacturers.delete',
            'label' => 'Delete Manufacturer',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'manufacturers.settings',
            'label' => 'Manufacturer Settings',
            'note' => '',
            'display' => true,
        ),
    ),
//Company management
    'Companies Privilege' => array(
        array(
            'permission' => 'companies.view',
            'label' => 'View companies',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'companies.create',
            'label' => 'Create companies',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'companies.edit',
            'label' => 'Edit companies',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'companies.delete',
            'label' => 'Delete companies',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'companies.settings',
            'label' => 'Company Settings',
            'note' => '',
            'display' => true,
        ),
    ),
    //Location management
    'Locations Privilege' => array(
        array(
            'permission' => 'locations.view',
            'label' => 'View Location',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'locations.create',
            'label' => 'Create Location',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'locations.edit',
            'label' => 'Edit Location',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'locations.delete',
            'label' => 'Delete Location',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'locations.settings',
            'label' => 'Location Settings',
            'note' => '',
            'display' => true,
        ),
    ),
//    Action log management
    'Action Logs Privilege' => array(
        array(
            'permission' => 'action_logs.view',
            'label' => 'View Action Logs',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'action_logs.create',
            'label' => 'Create Action Logs',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'action_logs.edit',
            'label' => 'Edit Action Logs',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'action_logs.delete',
            'label' => 'Delete Action Logs',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'action_logs.settings',
            'label' => 'Action Log Settings',
            'note' => '',
            'display' => true,
        ),
    ),
// Item Movement
    'Item Movements Privilege' => array(
        array(
            'permission' => 'item_movements.view',
            'label' => 'View Item Movement',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_movements.create',
            'label' => 'Create Item Movement',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_movements.edit',
            'label' => 'Edit Item Movement',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_movements.delete',
            'label' => 'Delete Item Movement',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_movements.settings',
            'label' => 'Item Movement Settings',
            'note' => '',
            'display' => true,
        ),
    ),
// Item Transfers
    'Item Transfers Privilege' => array(
        array(
            'permission' => 'item_transfers.view',
            'label' => 'View Item Transfers',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_transfers.create',
            'label' => 'Create Item Transfers',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_transfers.edit',
            'label' => 'Edit Item Transfers',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_transfers.delete',
            'label' => 'Delete Item Transfers',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_transfers.approval',
            'label' => 'Item transfer approval',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'item_transfers.settings',
            'label' => 'Item Transfer Settings',
            'note' => '',
            'display' => true,
        ),
    ),
//  UOM
    'Unit Of Measure Privilege' => array(
        array(
            'permission' => 'units.view',
            'label' => 'View units',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'units.create',
            'label' => 'Create units',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'units.edit',
            'label' => 'Edit units',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'units.delete',
            'label' => 'Delete units',
            'note' => '',
            'display' => true,
        ),
        array(
            'permission' => 'units.settings',
            'label' => 'Unit Of Measure Settings',
            'note' => '',
            'display' => true,
        ),
    ),
);
